In [1]:
import pandas as pd
data=pd.read_csv("C:/Users/dheve/OneDrive/Desktop/course/tips.csv")
data 

total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]

In [2]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 244 entries, 0 to 243
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype  
---  ------      --------------  -----  
 0   total_bill  244 non-null    float64
 1   tip         244 non-null    float64
 2   sex         244 non-null    object 
 3   smoker      244 non-null    object 
 4   day         244 non-null    object 
 5   time        244 non-null    object 
 6   size        244 non-null    int64  
dtypes: float64(2), int64(1), object(4)
memory usage: 13.5+ KB


In [3]:
dataset_table=pd.crosstab(data['sex'],data['smoker'],margins=True)#margins give total count
dataset_table
#crosstab tells us the frequency of catagorical

smoker   No  Yes  All
sex                  
Female   54   33   87
Male     97   60  157
All     151   93  244

In [4]:
import seaborn as sns
import numpy as np
from scipy import stats
from scipy.stats import chi2_contingency


In [5]:
val=stats.chi2_contingency(dataset_table)
val
#0.00193: This is the Chi-squared statistic, which measures how much the observed frequencies deviate from the expected frequencies.
# This statistical test is commonly applied in situations where you want to determine whether there is a significant association between two categorical variables in a contingency table.
#0.9999995: This is the probability of observing the data,

#For example, the expected frequency for the first cell (first row, first column) is approximately 53.84, which suggests that if there were no association between the variables, 
#we would expect to see about 54 occurrences in that cell.

#Expected frequencies provide a critical point of reference in the Chi-squared test. By comparing observed frequencies to these expected counts, researchers can assess whether the observed 
#distributions are consistent with the assumption of independence or whether there is a significant association between the categorical variables.

Chi2ContingencyResult(statistic=0.001934818536627623, pvalue=0.9999995323613375, dof=4, expected_freq=array([[ 53.84016393,  33.15983607,  87.        ],
       [ 97.15983607,  59.84016393, 157.        ],
       [151.        ,  93.        , 244.        ]]))

In [14]:
observed_values=dataset_table.values
observed_values

array([[ 54,  33,  87],
       [ 97,  60, 157],
       [151,  93, 244]], dtype=int64)

In [7]:
Expected_Values=val[3]
Expected_Values

array([[ 53.84016393,  33.15983607,  87.        ],
       [ 97.15983607,  59.84016393, 157.        ],
       [151.        ,  93.        , 244.        ]])

In [8]:
no_of_rows=len(dataset_table.iloc[0:2,0])
no_of_columns=len(dataset_table.iloc[0,0:2])
ddof=(no_of_rows-1)*(no_of_columns-1)
alpha=0.05
ddof

1

In [9]:
from scipy.stats import chi2
chi_square=sum([(o-e)**2/e for o,e in zip(observed_values,Expected_Values)])#we are unziping it and putting it in o and e
chi_square
#tell how well the observed data fit the expected data  under the assumption of independence

array([0.00073745, 0.00119737, 0.        ])

In [10]:
chi_square_statistics=chi_square[0]+chi_square[1]
chi_square_statistics

0.001934818536627623

In [ ]:
critical_value=chi2.ppf(1-alpha,df=ddof)#probablity  point function eg What height is at the 90th percentile(critical value)
critical_value

3.841458820694124

In [12]:
if chi_square_statistics>=critical_value:
    print("reject null hypothsis")
else:
    print("accept null hypothsis")

accept null hypothsis


In [ ]:
p_value=1-chi2.cdf(x=chi_square_statistics,df=ddof)
p_value
#ccf:What’s the probability that a person is shorter than 180 cm (<=x,where we accept the null hypothsis)

0.964915107315732